import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {ContainerLabel} from "@/app/_components/ContainerLabel";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="m-auto max-w-5xl">
          <ContainerLabel name="Nested posts layout">
              {children}
          </ContainerLabel>
        </div>
      </body>
    </html>
  );
}
