import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import './globals.css';
import { ContainerLabel } from '@/app/_components/ContainerLabel';
import { ThemeProvider } from '@/app/_components/ThemeProvider';
import { Header } from '@/app/_components/Header/Header';
import { LeftMenu } from '@/app/_components/LeftMenu';
import { Footer } from '@/app/_components/Footer';

const geistSans = Geist({
    variable: '--font-geist-sans',
    weight: ['400', '700'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

/*
 * On navigation, layouts preserve state, remain interactive, and do not rerender.
 * */

export default function RootLayout({
    children,
    modal,
}: Readonly<{
    children: React.ReactNode;
    modal: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.className} antialiased`}
            >
                <ThemeProvider>
                    <div className="m-auto max-w-5xl">
                        <ContainerLabel name="Root layout">
                            <Header />
                            <div className="flex gap-4 mb-4">
                                <div className="shrink-0 basis-[200]">
                                    <LeftMenu />
                                </div>
                                <div className="flex-grow">
                                    {children}
                                </div>
                            </div>
                            <Footer />
                        </ContainerLabel>
                        {modal}
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
